### ISSUE TITLE
ImportError: No module named '_C'

### ISSUE THREAD

**Issue by SakLuvZz** [Xilinx/brevitas#139] opened 2020-05-03 16:13 UTC
I use pycharm to open this project on windows,and run Lenet code in Readme.md,got this problem,pytorch version 1.5.0,how to slove it

File "D:\pycharm\PythonProject\brevitas\brevitas\__init__.py", line 13, in <module>
    _, path, _ = imp.find_module("_C", [lib_dir])
  File "E:\zww\anaconda3\envs\pytorchnightly\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_C'

**Comment by Giuseppe5** [comment] 2020-05-03 16:20
We are actively working for the support to pytorch 1.5, which will be added in the next few days.

I suggest you to use one of the supported pytorch versions (from 1.1 to 1.4). 
Monitor the PR #119 and the Issues #122 and #125 to know when the official support for 1.5 is ready.

**Comment by SakLuvZz** [comment] 2020-05-03 17:12
when I use pytorch1.4.0,I got this error,

File "/home/zww/PycharmPro/ProProject/brevi/brevitas/brevitas/__init__.py", line 14, in <module>
    torch.ops.load_library(path)
  File "/home/zww/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/_ops.py", line 106, in load_library
    ctypes.CDLL(path)
  File "/home/zww/anaconda3/envs/pytorch/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/zww/PycharmPro/ProProject/brevi/brevitas/brevitas/_C.so: undefined symbol: _ZN5torch8autograd12VariableInfoC1ERKNS0_8VariableE

**Comment by Giuseppe5** [comment] 2020-05-03 17:24
Could you please specify your OS and python version? And also the commands you used to install brevitas

**Comment by SakLuvZz** [comment] 2020-05-03 17:42
I run cat /proc/version and I got this
Linux version 3.10.0-957.1.3.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Nov 29 14:49:43 UTC 2018

I use anaconda and conda  pytorch1.4.0 python3.8

**Comment by SakLuvZz** [comment] 2020-05-03 17:45
pip install -e .

**Comment by Giuseppe5** [comment] 2020-05-03 17:47
Could you please try and install the library with `pip install .`? 
It is likely that the problem will persist, as it looks like it is related to how the custom library is compiled. In our tests for linux we don't see any unexpected behaviour, but we'll try to look into it

**Comment by Giuseppe5** [comment] 2020-05-03 17:50
Also, after installing brevitas, try testing if it works from command line. Launch python from CL and execute `import brevitas` and `import brevitas.function.ops_ste`.
This is to understand if Pycharm is the cause of the problem.

**Comment by MikeKall** [comment] 2020-05-11 16:47
> File "/home/zww/PycharmPro/ProProject/brevi/brevitas/brevitas/**init**.py", line 14, in
> torch.ops.load_library(path)
> File "/home/zww/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/_ops.py", line 106, in load_library
> ctypes.CDLL(path)
> File "/home/zww/anaconda3/envs/pytorch/lib/python3.8/ctypes/**init**.py", line 373, in **init**
> self._handle = _dlopen(self._name, mode)
> OSError: /home/zww/PycharmPro/ProProject/brevi/brevitas/brevitas/_C.so: undefined symbol: _ZN5torch8autograd12VariableInfoC1ERKNS0_8VariableE



I have the same error when importing the brevitas library.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/brevitas/__init__.py", line 14, in <module>
    torch.ops.load_library(path)
  File "/usr/local/lib/python3.6/dist-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.6/dist-packages/brevitas/_C.so: undefined symbol: _ZTIN5torch8autograd4NodeE

I use Python 3.6.9 and pytorch 1.5.0
OS: Linux version 5.3.0-51-generic (buildd@lgw01-amd64-018) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020

Installation command: pip install git+https://github.com/Xilinx/brevitas.git

**Comment by volcacius** [comment] 2020-05-11 17:28
I have merged the fixes for Pytorch 1.5.0 into master, can you please try again and let me know? Thanks.

**Comment by MikeKall** [comment] 2020-05-11 18:50
It works, thanks!

**Comment by volcacius** [comment] 2020-05-11 18:53
Great, closing then.

**Closed by volcacius** 2020-05-11 18:53 UTC
