### ISSUE TITLE
ModuleNotFoundError: No module named 'brevitas.function.ops_ste'

### ISSUE THREAD

**Issue by dalongmaoxiaotushu** [Xilinx/brevitas#69] opened 2020-03-25 14:58 UTC
I clone your brevitas repo and run pip install -e . but the setup.py file does not generate ops_ste.py file from ops_ste.py.template,I can not find ops_ste.py under brevitas/function/ and get this problem ,what is wrong with it ?

**Comment by Giuseppe5** [comment] 2020-03-25 15:56
This is a regression with respect to the current README.md, due to a recent refactor of the library and its installation process. We are working to solve it.

In the meantime, try installing Breivtas with `pip install .` and in the building directory, under brevitas/function there should be also the file ops_ste.py

**Comment by Giuseppe5** [comment] 2020-03-30 20:24
The fix has been merged in the dev and master branches.
Feel free to try that everything work as expected. 
We added tests to verify that the ops_ste.py file is correct generated also in develop mode.

**Closed by Giuseppe5** 2020-03-30 20:24 UTC
